version: '3'

services:
  webclient:
    image: webclient
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
    ## set your startup file here
    command: [nginx-debug, '-g', 'daemon off;']
